### ISSUE TITLE
Plans to open source the project?

### ISSUE THREAD

**Issue by yahoopete** [alphagov/forms#109]
Hey team, wondered if you have any plans or timings to open source the forms solution? Keep up the great work, it's coming along brilliantly!

Pete

**Comment by DavidBiddle** [comment]
Hi @yahoopete 

Sorry for the slow response on this! Our core applications are all already open source and MIT licensed - here are the repos:

- [forms-admin](https://github.com/alphagov/forms-admin) - our application for building forms.
- [forms-api](https://github.com/alphagov/forms-api) - our application for storing and serving form definitions.
- [forms-runner](https://github.com/alphagov/forms-runner) - our application for hosting forms, so that they can be filled in by members of the public.
- [forms-e2e-tests](https://github.com/alphagov/forms-e2e-tests) - end-to-end tests for the service.
- [forms-product-page](https://github.com/alphagov/forms-product-page) - our product pages, as seen at https://forms.service.gov.uk/
- [forms-prototypes](https://github.com/alphagov/forms-prototypes) - our prototypes, used for user research and design exploration.
- [govuk-forms-markdown](https://github.com/alphagov/govuk-forms-markdown) - our gem for rendering the limited subset of markdown we support.

We hadn't signposted those very well, so thanks for the issue! We've now added links to these in this repo's README to make this clearer. We'll keep that list updated if we add any new repos.
